<<<<<<< HEAD
import "./globals.css";
import Link from "next/link";

export const metadata = {
  title: "Trade Journal",
  description: "Trading Journal personale",
=======
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
>>>>>>> 9a907855d172c733c89957fb25b7e0babcbc0ab0
};

export default function RootLayout({
  children,
<<<<<<< HEAD
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="it">
      <body className="bg-[#020617] text-white">

        {/* 🌐 NAVBAR GLOBALE */}
        <nav className="w-full bg-slate-900 border-b border-slate-800 px-6 py-4">
          <div className="max-w-6xl mx-auto flex items-center justify-between">

            <h1 className="text-xl font-bold text-blue-400">
              Trade Journal
            </h1>

            <div className="flex gap-6 text-sm">
              <Link href="/dashboard" className="hover:text-blue-400 transition">
                Dashboard
              </Link>

              <Link href="/journal" className="hover:text-blue-400 transition">
                Journal
              </Link>

              <Link href="/statistics" className="hover:text-blue-400 transition">
                Statistiche
              </Link>
            </div>

          </div>
        </nav>

        <main className="pt-6">{children}</main>

=======
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
>>>>>>> 9a907855d172c733c89957fb25b7e0babcbc0ab0
      </body>
    </html>
  );
}
